spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/instagram_db
    username: asus
    password: asus@5683
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
